# Generated by Django 5.0.6 on 2024-06-03 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedig', '0003_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_orcamento', models.CharField(max_length=255)),
                ('nome_subestacao', models.CharField(max_length=255)),
                ('macroregiao', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('ano_referencia', models.IntegerField()),
                ('mes_referencia', models.CharField(max_length=255)),
                ('tipo_instalacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensao_primaria', models.IntegerField()),
                ('arranjo', models.CharField(max_length=255)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedig.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='ModuloManobra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sincronizacao_disjuntor', models.CharField(max_length=255)),
                ('tipo_aplicacao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
                ('patio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedig.patio')),
            ],
        ),
        migrations.CreateModel(
            name='ModuloEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipamento', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('patio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedig.patio')),
            ],
        ),
    ]
