# Generated by Django 5.0.6 on 2024-06-03 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedig', '0005_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
